import { add } from "date-fns";

function fromToday(numDays: number, withTime = false): string {
  const date = add(new Date(), { days: numDays });
  if (!withTime) date.setUTCHours(0, 0, 0, 0);
  return date.toISOString().slice(0, -1);
}

export const bookings = [
  {
    created_at: fromToday(-60, true),
    room_number: 5,
    guest_id: 50,
    stay: 19,
    checkin_date: fromToday(-1),
    checkout_date: fromToday(18),
    booking_status: "check-in",
    amount: 1368.39,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-38, true),
    room_number: 6,
    guest_id: 142,
    stay: 17,
    checkin_date: fromToday(-29),
    checkout_date: fromToday(-12),
    booking_status: "check-in",
    amount: 2823.39,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-34, true),
    room_number: 5,
    guest_id: 572,
    stay: 29,
    checkin_date: fromToday(-11),
    checkout_date: fromToday(18),
    booking_status: "unconfirmed",
    amount: 1357.48,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-15, true),
    room_number: 4,
    guest_id: 810,
    stay: 3,
    checkin_date: fromToday(-23),
    checkout_date: fromToday(-20),
    booking_status: "check-in",
    amount: 3053.04,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-80, true),
    room_number: 1,
    guest_id: 283,
    stay: 30,
    checkin_date: fromToday(-18),
    checkout_date: fromToday(12),
    booking_status: "unconfirmed",
    amount: 672.59,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-49, true),
    room_number: 3,
    guest_id: 91,
    stay: 8,
    checkin_date: fromToday(13),
    checkout_date: fromToday(21),
    booking_status: "check-out",
    amount: 2307.14,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-83, true),
    room_number: 2,
    guest_id: 608,
    stay: 17,
    checkin_date: fromToday(33),
    checkout_date: fromToday(50),
    booking_status: "check-in",
    amount: 3015.42,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-32, true),
    room_number: 3,
    guest_id: 740,
    stay: 25,
    checkin_date: fromToday(50),
    checkout_date: fromToday(75),
    booking_status: "check-out",
    amount: 4518.13,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-66, true),
    room_number: 5,
    guest_id: 809,
    stay: 7,
    checkin_date: fromToday(9),
    checkout_date: fromToday(16),
    booking_status: "check-in",
    amount: 2791.03,
    total_persons: 4,
    breakfast: false,
  },
  {
    created_at: fromToday(-33, true),
    room_number: 3,
    guest_id: 992,
    stay: 10,
    checkin_date: fromToday(-24),
    checkout_date: fromToday(-14),
    booking_status: "check-out",
    amount: 4369.44,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-93, true),
    room_number: 6,
    guest_id: 156,
    stay: 8,
    checkin_date: fromToday(50),
    checkout_date: fromToday(58),
    booking_status: "check-in",
    amount: 1042.78,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-23, true),
    room_number: 1,
    guest_id: 855,
    stay: 8,
    checkin_date: fromToday(-21),
    checkout_date: fromToday(-13),
    booking_status: "check-out",
    amount: 3699.01,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-36, true),
    room_number: 5,
    guest_id: 797,
    stay: 24,
    checkin_date: fromToday(7),
    checkout_date: fromToday(31),
    booking_status: "check-out",
    amount: 1875.34,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-88, true),
    room_number: 8,
    guest_id: 975,
    stay: 14,
    checkin_date: fromToday(-33),
    checkout_date: fromToday(-19),
    booking_status: "check-in",
    amount: 3143.33,
    total_persons: 3,
    breakfast: false,
  },
  {
    created_at: fromToday(-80, true),
    room_number: 2,
    guest_id: 646,
    stay: 28,
    checkin_date: fromToday(20),
    checkout_date: fromToday(48),
    booking_status: "check-in",
    amount: 1742.8,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-1, true),
    room_number: 1,
    guest_id: 208,
    stay: 22,
    checkin_date: fromToday(8),
    checkout_date: fromToday(30),
    booking_status: "check-in",
    amount: 184.26,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-35, true),
    room_number: 6,
    guest_id: 575,
    stay: 15,
    checkin_date: fromToday(24),
    checkout_date: fromToday(39),
    booking_status: "check-out",
    amount: 3833.68,
    total_persons: 4,
    breakfast: false,
  },
  {
    created_at: fromToday(-7, true),
    room_number: 5,
    guest_id: 217,
    stay: 13,
    checkin_date: fromToday(-50),
    checkout_date: fromToday(-37),
    booking_status: "check-out",
    amount: 1795.35,
    total_persons: 7,
    breakfast: false,
  },
  {
    created_at: fromToday(-69, true),
    room_number: 3,
    guest_id: 300,
    stay: 27,
    checkin_date: fromToday(-42),
    checkout_date: fromToday(-15),
    booking_status: "check-in",
    amount: 402.69,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-67, true),
    room_number: 4,
    guest_id: 778,
    stay: 26,
    checkin_date: fromToday(20),
    checkout_date: fromToday(46),
    booking_status: "unconfirmed",
    amount: 4649.55,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-38, true),
    room_number: 6,
    guest_id: 54,
    stay: 27,
    checkin_date: fromToday(-4),
    checkout_date: fromToday(23),
    booking_status: "check-in",
    amount: 4657.23,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-32, true),
    room_number: 3,
    guest_id: 505,
    stay: 28,
    checkin_date: fromToday(41),
    checkout_date: fromToday(69),
    booking_status: "check-in",
    amount: 4121.49,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-39, true),
    room_number: 5,
    guest_id: 9,
    stay: 25,
    checkin_date: fromToday(-31),
    checkout_date: fromToday(-6),
    booking_status: "unconfirmed",
    amount: 479.32,
    total_persons: 4,
    breakfast: false,
  },
  {
    created_at: fromToday(-91, true),
    room_number: 8,
    guest_id: 257,
    stay: 8,
    checkin_date: fromToday(-31),
    checkout_date: fromToday(-23),
    booking_status: "unconfirmed",
    amount: 2609.93,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-85, true),
    room_number: 5,
    guest_id: 642,
    stay: 21,
    checkin_date: fromToday(23),
    checkout_date: fromToday(44),
    booking_status: "check-in",
    amount: 3643.69,
    total_persons: 8,
    breakfast: false,
  },
  {
    created_at: fromToday(-40, true),
    room_number: 2,
    guest_id: 372,
    stay: 28,
    checkin_date: fromToday(4),
    checkout_date: fromToday(32),
    booking_status: "check-out",
    amount: 4753.78,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-54, true),
    room_number: 4,
    guest_id: 119,
    stay: 5,
    checkin_date: fromToday(37),
    checkout_date: fromToday(42),
    booking_status: "unconfirmed",
    amount: 3839.1,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-10, true),
    room_number: 4,
    guest_id: 931,
    stay: 19,
    checkin_date: fromToday(-41),
    checkout_date: fromToday(-22),
    booking_status: "check-in",
    amount: 2975.72,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-79, true),
    room_number: 6,
    guest_id: 102,
    stay: 20,
    checkin_date: fromToday(-10),
    checkout_date: fromToday(10),
    booking_status: "check-out",
    amount: 3664.82,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-68, true),
    room_number: 5,
    guest_id: 264,
    stay: 28,
    checkin_date: fromToday(34),
    checkout_date: fromToday(62),
    booking_status: "check-in",
    amount: 2763.28,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-95, true),
    room_number: 7,
    guest_id: 926,
    stay: 30,
    checkin_date: fromToday(25),
    checkout_date: fromToday(55),
    booking_status: "check-in",
    amount: 3953.45,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-87, true),
    room_number: 8,
    guest_id: 236,
    stay: 4,
    checkin_date: fromToday(-30),
    checkout_date: fromToday(-26),
    booking_status: "check-out",
    amount: 2803.88,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-9, true),
    room_number: 2,
    guest_id: 119,
    stay: 14,
    checkin_date: fromToday(14),
    checkout_date: fromToday(28),
    booking_status: "check-out",
    amount: 2902.59,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-58, true),
    room_number: 2,
    guest_id: 287,
    stay: 22,
    checkin_date: fromToday(35),
    checkout_date: fromToday(57),
    booking_status: "check-out",
    amount: 3899.91,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-73, true),
    room_number: 5,
    guest_id: 865,
    stay: 30,
    checkin_date: fromToday(26),
    checkout_date: fromToday(56),
    booking_status: "unconfirmed",
    amount: 507.34,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-5, true),
    room_number: 6,
    guest_id: 483,
    stay: 3,
    checkin_date: fromToday(3),
    checkout_date: fromToday(6),
    booking_status: "check-out",
    amount: 2430.52,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-41, true),
    room_number: 4,
    guest_id: 732,
    stay: 3,
    checkin_date: fromToday(-50),
    checkout_date: fromToday(-47),
    booking_status: "unconfirmed",
    amount: 959.53,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-35, true),
    room_number: 8,
    guest_id: 765,
    stay: 30,
    checkin_date: fromToday(15),
    checkout_date: fromToday(45),
    booking_status: "check-out",
    amount: 2680.71,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-32, true),
    room_number: 3,
    guest_id: 474,
    stay: 22,
    checkin_date: fromToday(50),
    checkout_date: fromToday(72),
    booking_status: "check-out",
    amount: 3153.11,
    total_persons: 8,
    breakfast: false,
  },
  {
    created_at: fromToday(-18, true),
    room_number: 4,
    guest_id: 824,
    stay: 3,
    checkin_date: fromToday(-20),
    checkout_date: fromToday(-17),
    booking_status: "check-in",
    amount: 4846.41,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-13, true),
    room_number: 8,
    guest_id: 336,
    stay: 4,
    checkin_date: fromToday(-44),
    checkout_date: fromToday(-40),
    booking_status: "check-out",
    amount: 4228.56,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-62, true),
    room_number: 2,
    guest_id: 84,
    stay: 11,
    checkin_date: fromToday(15),
    checkout_date: fromToday(26),
    booking_status: "check-out",
    amount: 4644.18,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-29, true),
    room_number: 3,
    guest_id: 627,
    stay: 12,
    checkin_date: fromToday(-2),
    checkout_date: fromToday(10),
    booking_status: "check-out",
    amount: 2435.95,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-46, true),
    room_number: 1,
    guest_id: 119,
    stay: 24,
    checkin_date: fromToday(-44),
    checkout_date: fromToday(-20),
    booking_status: "unconfirmed",
    amount: 1541.52,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-83, true),
    room_number: 6,
    guest_id: 489,
    stay: 5,
    checkin_date: fromToday(9),
    checkout_date: fromToday(14),
    booking_status: "check-out",
    amount: 1059.44,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-26, true),
    room_number: 2,
    guest_id: 52,
    stay: 13,
    checkin_date: fromToday(15),
    checkout_date: fromToday(28),
    booking_status: "unconfirmed",
    amount: 3349.63,
    total_persons: 4,
    breakfast: false,
  },
  {
    created_at: fromToday(-30, true),
    room_number: 7,
    guest_id: 331,
    stay: 19,
    checkin_date: fromToday(43),
    checkout_date: fromToday(62),
    booking_status: "check-in",
    amount: 849.69,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-8, true),
    room_number: 4,
    guest_id: 610,
    stay: 8,
    checkin_date: fromToday(-18),
    checkout_date: fromToday(-10),
    booking_status: "check-out",
    amount: 2224.14,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-32, true),
    room_number: 7,
    guest_id: 390,
    stay: 27,
    checkin_date: fromToday(-47),
    checkout_date: fromToday(-20),
    booking_status: "unconfirmed",
    amount: 2196.29,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-16, true),
    room_number: 5,
    guest_id: 765,
    stay: 14,
    checkin_date: fromToday(-45),
    checkout_date: fromToday(-31),
    booking_status: "check-out",
    amount: 814.8,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-33, true),
    room_number: 8,
    guest_id: 480,
    stay: 29,
    checkin_date: fromToday(-4),
    checkout_date: fromToday(25),
    booking_status: "check-in",
    amount: 4036.02,
    total_persons: 7,
    breakfast: false,
  },
  {
    created_at: fromToday(0, true),
    room_number: 4,
    guest_id: 55,
    stay: 9,
    checkin_date: fromToday(10),
    checkout_date: fromToday(19),
    booking_status: "check-out",
    amount: 1001.69,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-89, true),
    room_number: 7,
    guest_id: 646,
    stay: 14,
    checkin_date: fromToday(13),
    checkout_date: fromToday(27),
    booking_status: "check-in",
    amount: 2227.77,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-34, true),
    room_number: 3,
    guest_id: 638,
    stay: 30,
    checkin_date: fromToday(-28),
    checkout_date: fromToday(2),
    booking_status: "unconfirmed",
    amount: 306.48,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-25, true),
    room_number: 7,
    guest_id: 131,
    stay: 14,
    checkin_date: fromToday(18),
    checkout_date: fromToday(32),
    booking_status: "unconfirmed",
    amount: 527.37,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-31, true),
    room_number: 4,
    guest_id: 242,
    stay: 20,
    checkin_date: fromToday(-39),
    checkout_date: fromToday(-19),
    booking_status: "check-out",
    amount: 2057.76,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-21, true),
    room_number: 8,
    guest_id: 830,
    stay: 20,
    checkin_date: fromToday(-6),
    checkout_date: fromToday(14),
    booking_status: "check-out",
    amount: 4145.11,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-58, true),
    room_number: 2,
    guest_id: 294,
    stay: 23,
    checkin_date: fromToday(27),
    checkout_date: fromToday(50),
    booking_status: "unconfirmed",
    amount: 156.02,
    total_persons: 7,
    breakfast: false,
  },
  {
    created_at: fromToday(-41, true),
    room_number: 3,
    guest_id: 884,
    stay: 10,
    checkin_date: fromToday(12),
    checkout_date: fromToday(22),
    booking_status: "check-in",
    amount: 620.8,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-78, true),
    room_number: 3,
    guest_id: 80,
    stay: 11,
    checkin_date: fromToday(-37),
    checkout_date: fromToday(-26),
    booking_status: "unconfirmed",
    amount: 1836.54,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-47, true),
    room_number: 5,
    guest_id: 71,
    stay: 3,
    checkin_date: fromToday(-6),
    checkout_date: fromToday(-3),
    booking_status: "unconfirmed",
    amount: 4193.23,
    total_persons: 7,
    breakfast: false,
  },
  {
    created_at: fromToday(-98, true),
    room_number: 7,
    guest_id: 351,
    stay: 9,
    checkin_date: fromToday(20),
    checkout_date: fromToday(29),
    booking_status: "check-in",
    amount: 2266.86,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-17, true),
    room_number: 3,
    guest_id: 68,
    stay: 29,
    checkin_date: fromToday(-16),
    checkout_date: fromToday(13),
    booking_status: "check-in",
    amount: 1381.93,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-84, true),
    room_number: 4,
    guest_id: 171,
    stay: 18,
    checkin_date: fromToday(8),
    checkout_date: fromToday(26),
    booking_status: "unconfirmed",
    amount: 4776.32,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-17, true),
    room_number: 4,
    guest_id: 485,
    stay: 21,
    checkin_date: fromToday(-19),
    checkout_date: fromToday(2),
    booking_status: "check-in",
    amount: 4389.08,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-55, true),
    room_number: 6,
    guest_id: 975,
    stay: 18,
    checkin_date: fromToday(-38),
    checkout_date: fromToday(-20),
    booking_status: "unconfirmed",
    amount: 103.4,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-53, true),
    room_number: 7,
    guest_id: 2,
    stay: 18,
    checkin_date: fromToday(10),
    checkout_date: fromToday(28),
    booking_status: "unconfirmed",
    amount: 1210.02,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-55, true),
    room_number: 8,
    guest_id: 575,
    stay: 19,
    checkin_date: fromToday(20),
    checkout_date: fromToday(39),
    booking_status: "check-in",
    amount: 1737.23,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-30, true),
    room_number: 3,
    guest_id: 549,
    stay: 15,
    checkin_date: fromToday(33),
    checkout_date: fromToday(48),
    booking_status: "check-in",
    amount: 3419.96,
    total_persons: 3,
    breakfast: false,
  },
  {
    created_at: fromToday(-11, true),
    room_number: 6,
    guest_id: 160,
    stay: 28,
    checkin_date: fromToday(15),
    checkout_date: fromToday(43),
    booking_status: "check-out",
    amount: 4143.88,
    total_persons: 7,
    breakfast: false,
  },
  {
    created_at: fromToday(-28, true),
    room_number: 7,
    guest_id: 33,
    stay: 5,
    checkin_date: fromToday(-31),
    checkout_date: fromToday(-26),
    booking_status: "check-in",
    amount: 307.35,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-84, true),
    room_number: 1,
    guest_id: 889,
    stay: 30,
    checkin_date: fromToday(49),
    checkout_date: fromToday(79),
    booking_status: "check-in",
    amount: 4215.65,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-23, true),
    room_number: 8,
    guest_id: 883,
    stay: 17,
    checkin_date: fromToday(-2),
    checkout_date: fromToday(15),
    booking_status: "unconfirmed",
    amount: 531.47,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-3, true),
    room_number: 3,
    guest_id: 468,
    stay: 16,
    checkin_date: fromToday(9),
    checkout_date: fromToday(25),
    booking_status: "check-out",
    amount: 1245.65,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-61, true),
    room_number: 8,
    guest_id: 359,
    stay: 23,
    checkin_date: fromToday(50),
    checkout_date: fromToday(73),
    booking_status: "unconfirmed",
    amount: 4103.09,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-69, true),
    room_number: 7,
    guest_id: 133,
    stay: 17,
    checkin_date: fromToday(-24),
    checkout_date: fromToday(-7),
    booking_status: "check-in",
    amount: 4694.75,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-76, true),
    room_number: 8,
    guest_id: 734,
    stay: 20,
    checkin_date: fromToday(-24),
    checkout_date: fromToday(-4),
    booking_status: "check-in",
    amount: 2287.34,
    total_persons: 7,
    breakfast: false,
  },
  {
    created_at: fromToday(-86, true),
    room_number: 8,
    guest_id: 748,
    stay: 13,
    checkin_date: fromToday(35),
    checkout_date: fromToday(48),
    booking_status: "unconfirmed",
    amount: 1938.72,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-11, true),
    room_number: 6,
    guest_id: 849,
    stay: 28,
    checkin_date: fromToday(-43),
    checkout_date: fromToday(-15),
    booking_status: "check-in",
    amount: 1178.41,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-54, true),
    room_number: 4,
    guest_id: 202,
    stay: 6,
    checkin_date: fromToday(8),
    checkout_date: fromToday(14),
    booking_status: "unconfirmed",
    amount: 4871.77,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-33, true),
    room_number: 2,
    guest_id: 10,
    stay: 2,
    checkin_date: fromToday(40),
    checkout_date: fromToday(42),
    booking_status: "check-in",
    amount: 4093.34,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-93, true),
    room_number: 8,
    guest_id: 324,
    stay: 18,
    checkin_date: fromToday(-24),
    checkout_date: fromToday(-6),
    booking_status: "check-in",
    amount: 123.03,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-12, true),
    room_number: 6,
    guest_id: 145,
    stay: 12,
    checkin_date: fromToday(-28),
    checkout_date: fromToday(-16),
    booking_status: "check-out",
    amount: 4989.15,
    total_persons: 3,
    breakfast: false,
  },
  {
    created_at: fromToday(-96, true),
    room_number: 3,
    guest_id: 413,
    stay: 22,
    checkin_date: fromToday(-47),
    checkout_date: fromToday(-25),
    booking_status: "check-out",
    amount: 2038.94,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-77, true),
    room_number: 6,
    guest_id: 898,
    stay: 22,
    checkin_date: fromToday(12),
    checkout_date: fromToday(34),
    booking_status: "check-out",
    amount: 2041.89,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-8, true),
    room_number: 3,
    guest_id: 936,
    stay: 12,
    checkin_date: fromToday(17),
    checkout_date: fromToday(29),
    booking_status: "check-in",
    amount: 1977.19,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-33, true),
    room_number: 2,
    guest_id: 240,
    stay: 19,
    checkin_date: fromToday(36),
    checkout_date: fromToday(55),
    booking_status: "unconfirmed",
    amount: 1078.26,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-93, true),
    room_number: 6,
    guest_id: 108,
    stay: 6,
    checkin_date: fromToday(49),
    checkout_date: fromToday(55),
    booking_status: "unconfirmed",
    amount: 992.26,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-88, true),
    room_number: 7,
    guest_id: 450,
    stay: 11,
    checkin_date: fromToday(8),
    checkout_date: fromToday(19),
    booking_status: "check-out",
    amount: 1175.68,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-55, true),
    room_number: 8,
    guest_id: 662,
    stay: 7,
    checkin_date: fromToday(-29),
    checkout_date: fromToday(-22),
    booking_status: "unconfirmed",
    amount: 2178.75,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-35, true),
    room_number: 5,
    guest_id: 819,
    stay: 8,
    checkin_date: fromToday(-40),
    checkout_date: fromToday(-32),
    booking_status: "check-out",
    amount: 3897.75,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-46, true),
    room_number: 6,
    guest_id: 562,
    stay: 25,
    checkin_date: fromToday(10),
    checkout_date: fromToday(35),
    booking_status: "check-in",
    amount: 3486.83,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-91, true),
    room_number: 1,
    guest_id: 773,
    stay: 1,
    checkin_date: fromToday(22),
    checkout_date: fromToday(23),
    booking_status: "unconfirmed",
    amount: 4377.52,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-37, true),
    room_number: 8,
    guest_id: 264,
    stay: 30,
    checkin_date: fromToday(23),
    checkout_date: fromToday(53),
    booking_status: "unconfirmed",
    amount: 3251.13,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-87, true),
    room_number: 5,
    guest_id: 972,
    stay: 15,
    checkin_date: fromToday(10),
    checkout_date: fromToday(25),
    booking_status: "unconfirmed",
    amount: 4306.54,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-17, true),
    room_number: 6,
    guest_id: 837,
    stay: 17,
    checkin_date: fromToday(-33),
    checkout_date: fromToday(-16),
    booking_status: "check-in",
    amount: 2187.07,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-36, true),
    room_number: 3,
    guest_id: 60,
    stay: 16,
    checkin_date: fromToday(13),
    checkout_date: fromToday(29),
    booking_status: "check-out",
    amount: 1698.26,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-5, true),
    room_number: 3,
    guest_id: 617,
    stay: 22,
    checkin_date: fromToday(-38),
    checkout_date: fromToday(-16),
    booking_status: "check-out",
    amount: 3270.11,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-80, true),
    room_number: 4,
    guest_id: 823,
    stay: 28,
    checkin_date: fromToday(20),
    checkout_date: fromToday(48),
    booking_status: "unconfirmed",
    amount: 4302.74,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-35, true),
    room_number: 8,
    guest_id: 469,
    stay: 24,
    checkin_date: fromToday(-30),
    checkout_date: fromToday(-6),
    booking_status: "unconfirmed",
    amount: 2318.24,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-100, true),
    room_number: 7,
    guest_id: 412,
    stay: 5,
    checkin_date: fromToday(36),
    checkout_date: fromToday(41),
    booking_status: "check-out",
    amount: 4507.53,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-81, true),
    room_number: 7,
    guest_id: 981,
    stay: 20,
    checkin_date: fromToday(28),
    checkout_date: fromToday(48),
    booking_status: "check-in",
    amount: 4027.96,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-58, true),
    room_number: 2,
    guest_id: 873,
    stay: 2,
    checkin_date: fromToday(40),
    checkout_date: fromToday(42),
    booking_status: "check-out",
    amount: 711.45,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-60, true),
    room_number: 5,
    guest_id: 963,
    stay: 6,
    checkin_date: fromToday(-44),
    checkout_date: fromToday(-38),
    booking_status: "check-out",
    amount: 4637.88,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-57, true),
    room_number: 3,
    guest_id: 1000,
    stay: 25,
    checkin_date: fromToday(27),
    checkout_date: fromToday(52),
    booking_status: "check-in",
    amount: 180.84,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(0, true),
    room_number: 7,
    guest_id: 453,
    stay: 28,
    checkin_date: fromToday(34),
    checkout_date: fromToday(62),
    booking_status: "unconfirmed",
    amount: 596.38,
    total_persons: 4,
    breakfast: false,
  },
  {
    created_at: fromToday(-93, true),
    room_number: 7,
    guest_id: 386,
    stay: 11,
    checkin_date: fromToday(-12),
    checkout_date: fromToday(-1),
    booking_status: "check-out",
    amount: 2547.58,
    total_persons: 8,
    breakfast: false,
  },
  {
    created_at: fromToday(-15, true),
    room_number: 2,
    guest_id: 991,
    stay: 28,
    checkin_date: fromToday(-48),
    checkout_date: fromToday(-20),
    booking_status: "check-in",
    amount: 1280.0,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-7, true),
    room_number: 1,
    guest_id: 351,
    stay: 25,
    checkin_date: fromToday(-25),
    checkout_date: fromToday(0),
    booking_status: "check-in",
    amount: 4411.03,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-75, true),
    room_number: 2,
    guest_id: 931,
    stay: 24,
    checkin_date: fromToday(-32),
    checkout_date: fromToday(-8),
    booking_status: "check-in",
    amount: 3812.94,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-33, true),
    room_number: 6,
    guest_id: 434,
    stay: 10,
    checkin_date: fromToday(27),
    checkout_date: fromToday(37),
    booking_status: "check-out",
    amount: 2171.73,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-14, true),
    room_number: 5,
    guest_id: 969,
    stay: 7,
    checkin_date: fromToday(36),
    checkout_date: fromToday(43),
    booking_status: "unconfirmed",
    amount: 2218.81,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-80, true),
    room_number: 5,
    guest_id: 31,
    stay: 29,
    checkin_date: fromToday(2),
    checkout_date: fromToday(31),
    booking_status: "check-out",
    amount: 2135.23,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-15, true),
    room_number: 7,
    guest_id: 542,
    stay: 2,
    checkin_date: fromToday(19),
    checkout_date: fromToday(21),
    booking_status: "check-out",
    amount: 1205.97,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-44, true),
    room_number: 6,
    guest_id: 722,
    stay: 11,
    checkin_date: fromToday(37),
    checkout_date: fromToday(48),
    booking_status: "check-out",
    amount: 310.92,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-84, true),
    room_number: 3,
    guest_id: 653,
    stay: 30,
    checkin_date: fromToday(-8),
    checkout_date: fromToday(22),
    booking_status: "check-in",
    amount: 4867.68,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-33, true),
    room_number: 7,
    guest_id: 848,
    stay: 18,
    checkin_date: fromToday(-44),
    checkout_date: fromToday(-26),
    booking_status: "check-out",
    amount: 2915.48,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-70, true),
    room_number: 7,
    guest_id: 20,
    stay: 13,
    checkin_date: fromToday(-45),
    checkout_date: fromToday(-32),
    booking_status: "check-out",
    amount: 3216.59,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-86, true),
    room_number: 1,
    guest_id: 611,
    stay: 25,
    checkin_date: fromToday(-35),
    checkout_date: fromToday(-10),
    booking_status: "check-in",
    amount: 1737.61,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-24, true),
    room_number: 6,
    guest_id: 190,
    stay: 9,
    checkin_date: fromToday(8),
    checkout_date: fromToday(17),
    booking_status: "check-in",
    amount: 2087.18,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-78, true),
    room_number: 5,
    guest_id: 791,
    stay: 5,
    checkin_date: fromToday(15),
    checkout_date: fromToday(20),
    booking_status: "check-out",
    amount: 3347.11,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-100, true),
    room_number: 6,
    guest_id: 454,
    stay: 11,
    checkin_date: fromToday(-46),
    checkout_date: fromToday(-35),
    booking_status: "check-out",
    amount: 4128.53,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-91, true),
    room_number: 2,
    guest_id: 777,
    stay: 2,
    checkin_date: fromToday(50),
    checkout_date: fromToday(52),
    booking_status: "check-in",
    amount: 1342.11,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-83, true),
    room_number: 8,
    guest_id: 315,
    stay: 2,
    checkin_date: fromToday(18),
    checkout_date: fromToday(20),
    booking_status: "unconfirmed",
    amount: 4189.27,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-88, true),
    room_number: 1,
    guest_id: 51,
    stay: 15,
    checkin_date: fromToday(28),
    checkout_date: fromToday(43),
    booking_status: "check-out",
    amount: 3635.92,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-4, true),
    room_number: 3,
    guest_id: 957,
    stay: 11,
    checkin_date: fromToday(14),
    checkout_date: fromToday(25),
    booking_status: "check-in",
    amount: 2284.11,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-38, true),
    room_number: 4,
    guest_id: 243,
    stay: 29,
    checkin_date: fromToday(-19),
    checkout_date: fromToday(10),
    booking_status: "unconfirmed",
    amount: 1664.54,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-17, true),
    room_number: 6,
    guest_id: 100,
    stay: 14,
    checkin_date: fromToday(17),
    checkout_date: fromToday(31),
    booking_status: "unconfirmed",
    amount: 4410.17,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-46, true),
    room_number: 5,
    guest_id: 166,
    stay: 27,
    checkin_date: fromToday(-37),
    checkout_date: fromToday(-10),
    booking_status: "check-in",
    amount: 2589.44,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-74, true),
    room_number: 2,
    guest_id: 656,
    stay: 3,
    checkin_date: fromToday(35),
    checkout_date: fromToday(38),
    booking_status: "check-out",
    amount: 4488.85,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-36, true),
    room_number: 1,
    guest_id: 633,
    stay: 6,
    checkin_date: fromToday(-10),
    checkout_date: fromToday(-4),
    booking_status: "check-in",
    amount: 4705.44,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-90, true),
    room_number: 3,
    guest_id: 342,
    stay: 17,
    checkin_date: fromToday(36),
    checkout_date: fromToday(53),
    booking_status: "unconfirmed",
    amount: 4975.45,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-98, true),
    room_number: 7,
    guest_id: 959,
    stay: 18,
    checkin_date: fromToday(-42),
    checkout_date: fromToday(-24),
    booking_status: "unconfirmed",
    amount: 3470.55,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-2, true),
    room_number: 2,
    guest_id: 976,
    stay: 20,
    checkin_date: fromToday(-24),
    checkout_date: fromToday(-4),
    booking_status: "check-in",
    amount: 1564.29,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-83, true),
    room_number: 3,
    guest_id: 88,
    stay: 27,
    checkin_date: fromToday(-17),
    checkout_date: fromToday(10),
    booking_status: "check-in",
    amount: 670.91,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-93, true),
    room_number: 8,
    guest_id: 784,
    stay: 28,
    checkin_date: fromToday(32),
    checkout_date: fromToday(60),
    booking_status: "check-out",
    amount: 1166.98,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-54, true),
    room_number: 1,
    guest_id: 127,
    stay: 16,
    checkin_date: fromToday(8),
    checkout_date: fromToday(24),
    booking_status: "check-in",
    amount: 2425.88,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-11, true),
    room_number: 3,
    guest_id: 501,
    stay: 5,
    checkin_date: fromToday(19),
    checkout_date: fromToday(24),
    booking_status: "check-in",
    amount: 2919.13,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-50, true),
    room_number: 4,
    guest_id: 12,
    stay: 10,
    checkin_date: fromToday(-48),
    checkout_date: fromToday(-38),
    booking_status: "check-out",
    amount: 149.18,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-38, true),
    room_number: 2,
    guest_id: 588,
    stay: 18,
    checkin_date: fromToday(32),
    checkout_date: fromToday(50),
    booking_status: "unconfirmed",
    amount: 4304.75,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-51, true),
    room_number: 5,
    guest_id: 232,
    stay: 24,
    checkin_date: fromToday(41),
    checkout_date: fromToday(65),
    booking_status: "unconfirmed",
    amount: 2689.97,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-34, true),
    room_number: 3,
    guest_id: 127,
    stay: 18,
    checkin_date: fromToday(37),
    checkout_date: fromToday(55),
    booking_status: "unconfirmed",
    amount: 3246.11,
    total_persons: 8,
    breakfast: false,
  },
  {
    created_at: fromToday(-13, true),
    room_number: 1,
    guest_id: 839,
    stay: 24,
    checkin_date: fromToday(28),
    checkout_date: fromToday(52),
    booking_status: "unconfirmed",
    amount: 658.26,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-19, true),
    room_number: 7,
    guest_id: 128,
    stay: 8,
    checkin_date: fromToday(-2),
    checkout_date: fromToday(6),
    booking_status: "check-in",
    amount: 2161.95,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-41, true),
    room_number: 5,
    guest_id: 521,
    stay: 29,
    checkin_date: fromToday(33),
    checkout_date: fromToday(62),
    booking_status: "check-in",
    amount: 241.44,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-76, true),
    room_number: 5,
    guest_id: 331,
    stay: 2,
    checkin_date: fromToday(1),
    checkout_date: fromToday(3),
    booking_status: "check-in",
    amount: 3953.65,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-44, true),
    room_number: 8,
    guest_id: 821,
    stay: 2,
    checkin_date: fromToday(45),
    checkout_date: fromToday(47),
    booking_status: "check-in",
    amount: 3945.51,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-6, true),
    room_number: 6,
    guest_id: 837,
    stay: 9,
    checkin_date: fromToday(-15),
    checkout_date: fromToday(-6),
    booking_status: "check-out",
    amount: 4288.43,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-71, true),
    room_number: 2,
    guest_id: 171,
    stay: 5,
    checkin_date: fromToday(1),
    checkout_date: fromToday(6),
    booking_status: "unconfirmed",
    amount: 362.11,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-89, true),
    room_number: 7,
    guest_id: 271,
    stay: 26,
    checkin_date: fromToday(-43),
    checkout_date: fromToday(-17),
    booking_status: "unconfirmed",
    amount: 1844.35,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-47, true),
    room_number: 1,
    guest_id: 228,
    stay: 28,
    checkin_date: fromToday(-4),
    checkout_date: fromToday(24),
    booking_status: "check-in",
    amount: 4695.71,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(0, true),
    room_number: 4,
    guest_id: 422,
    stay: 1,
    checkin_date: fromToday(12),
    checkout_date: fromToday(13),
    booking_status: "check-in",
    amount: 4903.16,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-10, true),
    room_number: 4,
    guest_id: 71,
    stay: 12,
    checkin_date: fromToday(-4),
    checkout_date: fromToday(8),
    booking_status: "check-in",
    amount: 2921.2,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-83, true),
    room_number: 7,
    guest_id: 542,
    stay: 19,
    checkin_date: fromToday(39),
    checkout_date: fromToday(58),
    booking_status: "check-in",
    amount: 2037.55,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-94, true),
    room_number: 7,
    guest_id: 697,
    stay: 5,
    checkin_date: fromToday(-39),
    checkout_date: fromToday(-34),
    booking_status: "check-in",
    amount: 4813.98,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-99, true),
    room_number: 2,
    guest_id: 735,
    stay: 14,
    checkin_date: fromToday(19),
    checkout_date: fromToday(33),
    booking_status: "check-out",
    amount: 3578.83,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-27, true),
    room_number: 6,
    guest_id: 311,
    stay: 3,
    checkin_date: fromToday(21),
    checkout_date: fromToday(24),
    booking_status: "check-out",
    amount: 2882.38,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-78, true),
    room_number: 6,
    guest_id: 445,
    stay: 27,
    checkin_date: fromToday(-45),
    checkout_date: fromToday(-18),
    booking_status: "check-in",
    amount: 2004.05,
    total_persons: 3,
    breakfast: false,
  },
  {
    created_at: fromToday(-97, true),
    room_number: 1,
    guest_id: 301,
    stay: 17,
    checkin_date: fromToday(15),
    checkout_date: fromToday(32),
    booking_status: "check-out",
    amount: 60.97,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-24, true),
    room_number: 1,
    guest_id: 840,
    stay: 12,
    checkin_date: fromToday(-11),
    checkout_date: fromToday(1),
    booking_status: "check-out",
    amount: 841.64,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-28, true),
    room_number: 8,
    guest_id: 219,
    stay: 15,
    checkin_date: fromToday(15),
    checkout_date: fromToday(30),
    booking_status: "check-in",
    amount: 4935.61,
    total_persons: 5,
    breakfast: true,
  },
  {
    created_at: fromToday(-76, true),
    room_number: 5,
    guest_id: 524,
    stay: 16,
    checkin_date: fromToday(-2),
    checkout_date: fromToday(14),
    booking_status: "check-in",
    amount: 4862.42,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-91, true),
    room_number: 4,
    guest_id: 582,
    stay: 24,
    checkin_date: fromToday(5),
    checkout_date: fromToday(29),
    booking_status: "unconfirmed",
    amount: 564.38,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-38, true),
    room_number: 5,
    guest_id: 694,
    stay: 21,
    checkin_date: fromToday(-49),
    checkout_date: fromToday(-28),
    booking_status: "check-in",
    amount: 3375.8,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-51, true),
    room_number: 7,
    guest_id: 330,
    stay: 23,
    checkin_date: fromToday(-25),
    checkout_date: fromToday(-2),
    booking_status: "check-in",
    amount: 1972.99,
    total_persons: 4,
    breakfast: false,
  },
  {
    created_at: fromToday(-72, true),
    room_number: 1,
    guest_id: 819,
    stay: 28,
    checkin_date: fromToday(-36),
    checkout_date: fromToday(-8),
    booking_status: "check-in",
    amount: 2651.35,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-26, true),
    room_number: 4,
    guest_id: 878,
    stay: 4,
    checkin_date: fromToday(6),
    checkout_date: fromToday(10),
    booking_status: "check-out",
    amount: 2704.83,
    total_persons: 6,
    breakfast: false,
  },
  {
    created_at: fromToday(-29, true),
    room_number: 3,
    guest_id: 522,
    stay: 17,
    checkin_date: fromToday(-38),
    checkout_date: fromToday(-21),
    booking_status: "check-out",
    amount: 2090.72,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-87, true),
    room_number: 8,
    guest_id: 303,
    stay: 26,
    checkin_date: fromToday(22),
    checkout_date: fromToday(48),
    booking_status: "check-in",
    amount: 2270.34,
    total_persons: 3,
    breakfast: false,
  },
  {
    created_at: fromToday(-20, true),
    room_number: 8,
    guest_id: 716,
    stay: 9,
    checkin_date: fromToday(48),
    checkout_date: fromToday(57),
    booking_status: "check-out",
    amount: 4860.93,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-61, true),
    room_number: 3,
    guest_id: 641,
    stay: 22,
    checkin_date: fromToday(12),
    checkout_date: fromToday(34),
    booking_status: "unconfirmed",
    amount: 4096.54,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-13, true),
    room_number: 5,
    guest_id: 103,
    stay: 16,
    checkin_date: fromToday(44),
    checkout_date: fromToday(60),
    booking_status: "check-out",
    amount: 4698.26,
    total_persons: 7,
    breakfast: false,
  },
  {
    created_at: fromToday(-37, true),
    room_number: 1,
    guest_id: 791,
    stay: 1,
    checkin_date: fromToday(-50),
    checkout_date: fromToday(-49),
    booking_status: "check-in",
    amount: 2861.72,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-46, true),
    room_number: 1,
    guest_id: 49,
    stay: 11,
    checkin_date: fromToday(-10),
    checkout_date: fromToday(1),
    booking_status: "check-out",
    amount: 998.81,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-11, true),
    room_number: 2,
    guest_id: 244,
    stay: 3,
    checkin_date: fromToday(-18),
    checkout_date: fromToday(-15),
    booking_status: "check-in",
    amount: 3819.74,
    total_persons: 3,
    breakfast: false,
  },
  {
    created_at: fromToday(-20, true),
    room_number: 1,
    guest_id: 248,
    stay: 14,
    checkin_date: fromToday(-37),
    checkout_date: fromToday(-23),
    booking_status: "check-in",
    amount: 1788.89,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-89, true),
    room_number: 3,
    guest_id: 975,
    stay: 11,
    checkin_date: fromToday(-44),
    checkout_date: fromToday(-33),
    booking_status: "unconfirmed",
    amount: 950.1,
    total_persons: 2,
    breakfast: false,
  },
  {
    created_at: fromToday(-94, true),
    room_number: 2,
    guest_id: 631,
    stay: 7,
    checkin_date: fromToday(48),
    checkout_date: fromToday(55),
    booking_status: "check-out",
    amount: 3550.57,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-90, true),
    room_number: 4,
    guest_id: 268,
    stay: 1,
    checkin_date: fromToday(-24),
    checkout_date: fromToday(-23),
    booking_status: "unconfirmed",
    amount: 3697.77,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-16, true),
    room_number: 5,
    guest_id: 878,
    stay: 14,
    checkin_date: fromToday(28),
    checkout_date: fromToday(42),
    booking_status: "unconfirmed",
    amount: 2085.19,
    total_persons: 5,
    breakfast: false,
  },
  {
    created_at: fromToday(-9, true),
    room_number: 3,
    guest_id: 227,
    stay: 16,
    checkin_date: fromToday(14),
    checkout_date: fromToday(30),
    booking_status: "check-out",
    amount: 1596.71,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-76, true),
    room_number: 7,
    guest_id: 562,
    stay: 20,
    checkin_date: fromToday(35),
    checkout_date: fromToday(55),
    booking_status: "check-in",
    amount: 1401.0,
    total_persons: 3,
    breakfast: true,
  },
  {
    created_at: fromToday(-95, true),
    room_number: 4,
    guest_id: 461,
    stay: 20,
    checkin_date: fromToday(43),
    checkout_date: fromToday(63),
    booking_status: "unconfirmed",
    amount: 177.88,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-58, true),
    room_number: 3,
    guest_id: 488,
    stay: 28,
    checkin_date: fromToday(-40),
    checkout_date: fromToday(-12),
    booking_status: "unconfirmed",
    amount: 1346.44,
    total_persons: 8,
    breakfast: false,
  },
  {
    created_at: fromToday(-76, true),
    room_number: 1,
    guest_id: 927,
    stay: 25,
    checkin_date: fromToday(30),
    checkout_date: fromToday(55),
    booking_status: "check-out",
    amount: 503.98,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-94, true),
    room_number: 4,
    guest_id: 994,
    stay: 23,
    checkin_date: fromToday(-13),
    checkout_date: fromToday(10),
    booking_status: "check-in",
    amount: 1375.61,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-80, true),
    room_number: 4,
    guest_id: 315,
    stay: 1,
    checkin_date: fromToday(-34),
    checkout_date: fromToday(-33),
    booking_status: "unconfirmed",
    amount: 2740.62,
    total_persons: 2,
    breakfast: true,
  },
  {
    created_at: fromToday(-17, true),
    room_number: 2,
    guest_id: 801,
    stay: 8,
    checkin_date: fromToday(29),
    checkout_date: fromToday(37),
    booking_status: "check-in",
    amount: 3615.31,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-25, true),
    room_number: 7,
    guest_id: 366,
    stay: 16,
    checkin_date: fromToday(-17),
    checkout_date: fromToday(-1),
    booking_status: "check-in",
    amount: 3308.35,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-88, true),
    room_number: 8,
    guest_id: 803,
    stay: 11,
    checkin_date: fromToday(42),
    checkout_date: fromToday(53),
    booking_status: "unconfirmed",
    amount: 1696.78,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-74, true),
    room_number: 7,
    guest_id: 72,
    stay: 6,
    checkin_date: fromToday(-25),
    checkout_date: fromToday(-19),
    booking_status: "check-out",
    amount: 3291.11,
    total_persons: 8,
    breakfast: false,
  },
  {
    created_at: fromToday(-36, true),
    room_number: 6,
    guest_id: 560,
    stay: 11,
    checkin_date: fromToday(34),
    checkout_date: fromToday(45),
    booking_status: "check-out",
    amount: 1565.04,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-13, true),
    room_number: 7,
    guest_id: 338,
    stay: 12,
    checkin_date: fromToday(-46),
    checkout_date: fromToday(-34),
    booking_status: "check-in",
    amount: 2204.05,
    total_persons: 3,
    breakfast: false,
  },
  {
    created_at: fromToday(-45, true),
    room_number: 2,
    guest_id: 246,
    stay: 22,
    checkin_date: fromToday(42),
    checkout_date: fromToday(64),
    booking_status: "unconfirmed",
    amount: 458.14,
    total_persons: 4,
    breakfast: true,
  },
  {
    created_at: fromToday(-96, true),
    room_number: 2,
    guest_id: 785,
    stay: 5,
    checkin_date: fromToday(-16),
    checkout_date: fromToday(-11),
    booking_status: "unconfirmed",
    amount: 4321.49,
    total_persons: 6,
    breakfast: true,
  },
  {
    created_at: fromToday(-100, true),
    room_number: 2,
    guest_id: 854,
    stay: 17,
    checkin_date: fromToday(27),
    checkout_date: fromToday(44),
    booking_status: "check-in",
    amount: 1634.2,
    total_persons: 1,
    breakfast: true,
  },
  {
    created_at: fromToday(-64, true),
    room_number: 4,
    guest_id: 90,
    stay: 6,
    checkin_date: fromToday(-46),
    checkout_date: fromToday(-40),
    booking_status: "check-in",
    amount: 1761.21,
    total_persons: 1,
    breakfast: false,
  },
  {
    created_at: fromToday(-71, true),
    room_number: 4,
    guest_id: 614,
    stay: 16,
    checkin_date: fromToday(-16),
    checkout_date: fromToday(0),
    booking_status: "unconfirmed",
    amount: 3330.75,
    total_persons: 8,
    breakfast: true,
  },
  {
    created_at: fromToday(-36, true),
    room_number: 1,
    guest_id: 683,
    stay: 29,
    checkin_date: fromToday(-6),
    checkout_date: fromToday(23),
    booking_status: "check-out",
    amount: 3627.19,
    total_persons: 7,
    breakfast: true,
  },
  {
    created_at: fromToday(-1, true),
    room_number: 4,
    guest_id: 524,
    stay: 1,
    checkin_date: fromToday(-50),
    checkout_date: fromToday(-49),
    booking_status: "check-out",
    amount: 3765.64,
    total_persons: 4,
    breakfast: false,
  },
];
